name: Tests

on:
  # Add the triggers as required
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'
  schedule:
    # * is a special character in YAML so you have to quote this string
    # This example triggers the workflow every day at 6:00 and 18:00 UTC:
    - cron:  '0 6,18 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      LT_USERNAME: ${{ secrets.LT_USERNAME }}
      LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}

    strategy:
      matrix:
        # Specify as per the service requirements
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test

      - name: Step for push event
        run: |
          echo "This is a push event!"
          echo "The latest commitId "
          echo "::set-output name=COMMIT_ID::$(git log -1 --format='%H')"
        if: github.event_name == 'push'

      - name: Step for pull_request event
        run: |
          echo "This is a pull_request event!"
          echo "The latest commitId $(git log -n 2 --format="%H" | tail -n 1)"
          echo "::set-output name=COMMIT_ID::$(git log -n 2 --format="%H" | tail -n 1)"
        if: github.event_name == 'pull_request'

      - name: Create Github URL
        run: |
          API_HOST=https://api.github.com
          GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/${{ steps.vars.outputs.COMMIT_ID }}
          echo "GITHUB_URL: $GITHUB_URL"
          echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV

      - name: Execute SmartUI Test
        run: npm run test-smartui      




